@rootUrl=http://localhost:4000
###
GET {{rootUrl}}/api/restaurants 

###
GET {{rootUrl}}/api/restaurant-Items/67fa103a1a3bdbc980559239

###
POST {{rootUrl}}/api/add-foodItem 
Content-Type: application/json 

{
    "foodName": "veg-pizza",
    "foodImage":"https://res.cloudinary.com/dalvkmppv/image/upload/v1746273650/veg-pizza_nyj9ba.jpg",
    "price": 350,
    "category": "Veg",
    "description": "This is a sample Pizza",
    "restaurantId": "67fa636b52c611874a6a3bf1"
}